### ISSUE TITLE
Set the project

### ISSUE THREAD

**Issue by Soy-Bin** [practice-githubflow-8/Pig-Dice-Game#1]
## Description

Set the project
Initialize the repository and files

## Tasks
- [x] create issues
- [x] create a project board
- [x] create .gitignore
- [x] create index.html
- [x] create script.js
- [x] create style.css
- [x] add images of dice
- [x] update README.md

## References
- [Pig Dice Game - Github](https://github.com/catherineisonline/pig-dice-game)
