### ISSUE TITLE
Implement index.html

### ISSUE THREAD

**Issue by Soy-Bin** [practice-githubflow-8/Pig-Dice-Game#2]
## Description

Implement index.html
Implement pig dice web page

## Tasks
- [x] initialize index.html
- [ ] implement head
- [ ] implement body - section : player-cards
- [ ]  implement body - buttons

## References
- [pig dice - code](https://github.com/catherineisonline/pig-dice-game/commit/45868d8be851bb31a28d4ee7fb31715d06b0768c)
