### ISSUE TITLE
Implement script.js

### ISSUE THREAD

**Issue by Soy-Bin** [practice-githubflow-8/Pig-Dice-Game#3]
## Description

Implement script.js
implement to move dice and get the score

## Tasks
- [ ] initialize scripts.js
- [ ] function : playerSwitching 
- [ ] function: rollDice.addEventListener 
- [ ] function: holdDice.addEventListener

## References
- [pig dice - code](https://github.com/catherineisonline/pig-dice-game/commit/45868d8be851bb31a28d4ee7fb31715d06b0768c#diff-ed3ee7e0beea2498ff3b8ca85973d122fc6fa3d585d62b5807ec034d0cf076b3)
